del *.ncb /f /S
del *.plg /f /S
del *.pch /f /S
del *.idb /f /S
del *.ilk /f /S
del *.pdb /f /S
del *.obj /f /S
del *.exp /f /S
del *.aps /f /S
del *.opt /f /S
del *.sdf /f /S
del *.ipch /f /S
del *.tlog /f /S
del *.log /f /S